### ISSUE TITLE
No such file exists error

### ISSUE THREAD

**Issue by mahdikarimi5509** [e1732a364fed/vsb#1]
I got this error, where did I go wrong?

AILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find :xx:.
     Searched in the following locations:
       - file:/C:/Users/mk/Desktop/vsb-main/android/app/libs/xx.aar
     Required by:
         project :app

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 15s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by e1732a364fed** [comment]
写了 xx.aar

你要到 https://github.com/e1732a364fed/v2ray_simple 项目编译出 aar 后放入指定位置
